/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class MutiMatrix */

#ifndef _Included_MutiMatrix
#define _Included_MutiMatrix
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     MutiMatrix
 * Method:    vectorMutiMatrix
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_MutiMatrix_vectorMutiMatrix
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     MutiMatrix
 * Method:    matrixMutiVector
 * Signature: ([D[D)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_MutiMatrix_matrixMutiVector
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

/*
 * Class:     MutiMatrix
 * Method:    matrixMutiMatrix
 * Signature: ([D[DI)[D
 */
JNIEXPORT jdoubleArray JNICALL Java_MutiMatrix_matrixMutiMatrix
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray, jint);

/*
 * Class:     MutiMatrix
 * Method:    distance
 * Signature: ([D[D)D
 */
JNIEXPORT jdouble JNICALL Java_MutiMatrix_distance
  (JNIEnv *, jobject, jdoubleArray, jdoubleArray);

#ifdef __cplusplus
}
#endif
#endif
