/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class OwnMath */

#ifndef _Included_OwnMath
#define _Included_OwnMath
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     OwnMath
 * Method:    add
 * Signature: (DD)D
 */
JNIEXPORT jdouble JNICALL Java_OwnMath_add
  (JNIEnv *, jobject, jdouble, jdouble);

#ifdef __cplusplus
}
#endif
#endif
